services:
  rt-client-customer:
    image: ${REGISTRY}/rt-client-customer:latest
    build:
      context: ..
      no_cache: true
      dockerfile: apps/customer/Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
  rt-client-admin:
    image: ${REGISTRY}/rt-client-admin:latest
    build:
      context: ..
      no_cache: true
      dockerfile: apps/admin/Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
  rt-client-seller:
    image: ${REGISTRY}/rt-client-seller:latest
    build:
      context: ..
      no_cache: true
      dockerfile: apps/seller/Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}