services:
  rt-client-customer:
    image: ${REGISTRY}/rt-client-customer:${TAG:-latest}
    build:
      context: ..
      no_cache: true
      dockerfile: apps/customer/Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
        - NODE_ENV=production
    profiles:
      - customer
      - build
  rt-client-admin:
    image: ${REGISTRY}/rt-client-admin:${TAG:-latest}
    build:
      context: ..
      no_cache: true
      dockerfile: apps/admin/Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
        - NODE_ENV=production
    profiles:
      - admin
      - build
  rt-client-seller:
    image: ${REGISTRY}/rt-client-seller:${TAG:-latest}
    build:
      context: ..
      no_cache: true
      dockerfile: apps/seller/Dockerfile
      args:
        - API_BASE_URL=${API_BASE_URL}
        - NODE_ENV=production
    profiles:
      - seller
      - build
