#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if command -v powershell.exe >/dev/null 2>&1; then
  echo "Detected Windows - using PowerShell"
  powershell.exe -Command "yarn format"
elif command -v pwsh >/dev/null 2>&1; then
  echo "Detected PowerShell Core"
  pwsh -Command "yarn format"
else
  echo "Using standard shell"
  yarn format
fi