name: Deploy to Dev Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-images:
    name: Build Image
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-image.yaml
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit

  deploy-client:
    name: Deploy Client
    needs: build-images
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      actor: ${{ github.actor }}
      repository: ${{ github.repository }}
    secrets: inherit